name: Expo Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_KEY: ${{secrets.API_KEY}}
          envkey_AUTH_DOMAIN: ${{secrets.AUTH_DOMAIN}}
          envkey_PROJECT_ID: ${{secrets.PROJECT_ID}}
          envkey_STORAGE_BUCKET: ${{secrets.STORAGE_BUCKET}}
          envkey_MESSAGING_SENDER_ID: ${{secrets.MESSAGING_SENDER_ID}}
          envkey_APP_ID: ${{secrets.APP_ID}}
          directory: './'
          file_name: '.env'
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - run: yarn install
      - run: expo publish
        env:
          NODE_OPTIONS: --max_old_space_size=4096